[tool.poetry]
name = "las"
version = "0.1.0"
description = ""
authors = ["ChainHokes <k.nazar2003@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.23.0"
pytest = "^7.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
